# Phan tich va hien thi du lieu

In [7]:
v = list(range(1,6))
print(v)
print (v*2)


[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [9]:
import numpy as np
v = np.arange(1,6)
print(v)
print(v*2)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [11]:
x = ["apple", "banana", "cherry"] #list
x = ("apple", "banana", "cherry") #tuple
x = {"name" : "Tom", "age" : 20} #dict
x = {"apple", "banana", "cherry"} #set 

In [16]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a*b
print ('c=', c)
display(c)


c= [ 4 10 18]


array([ 4, 10, 18])

In [1]:
import numpy as np
a = np.zeros((2,2))
display(a)
b = np.ones((3,2))
display(b)
c = np.eye(1)
display(b)

display(a.ndim)


array([[0., 0.],
       [0., 0.]])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

2

In [2]:
import numpy as np
a = np.array([1,2,3,4,5])
display(a)

array([1, 2, 3, 4, 5])

# Ket thuc